### ISSUE TITLE
issues with gz'd files during make.contigs

### ISSUE THREAD

**Issue by rec3141** [mothur/mothur#320]
This may be two separate issues that involve running mothur v.1.39.5 on gzipped fastq files with very few sequences. I'm not sure if they're connected.

1) mothur segfaults using the ffastq/rfastq syntax

 ./mothur "#make.contigs(ffastq=test_1.fq.gz, rfastq=test_2.fq.gz)"

mO�R�0 is in your forward fastq file and not in your reverse file, please remove it using the remove.seqs command before proceeding.
Making contigs...
zsh: segmentation fault  ./mothur "#make.contigs(ffastq=test_1.fq.gz, rfastq=test_2.fq.gz)"
 
2) mothur spits out MILLIONS of errors when run using the .files syntax. 

./mothur "#make.contigs(file=test.files)"

I let it go for 5 minutes and it spit out the following error 60 million times (several Gb worth)

[WARNING]: missing sequence for , ignoring.[WARNING]: expected a name with + as a leading character, ignoring.[WARNING]: missing quality for , ignoring.[WARNING]: Blank fasta name, ignoring read.

Detected 59813656 [WARNING] messages, please review.

test.files
```test1	test_1.fq.gz	test_2.fq.gz```

test_1.fq
```
@M03580:15:000000000-AHFYP:1:1107:11796:2635 1:N:0:5
ATCGGTTGTGCCAGCCGCCGCGGTAATACAGGGGATGCAAGTGTTATCCGGAATTATTGGGCGTAAAGCGTCTGCAGGTTGATATTTAAGTCTTTTGTTAAACCTCCGGGCTCAACCCGGAATCTGCAAAGGAAACTATCTATCTTGAGTATGGTAGGGGTAAAGGGAATTTCCAGTGGAGCGGTGAAATGCGTAGATATTGGAAAGAACACCAACAGCGAAGGCACTTTACTGGGCCAGTACTGACACTCAGAGACGAAAGCTAGGGGAGCAAACAGGAGTATCAACCCTTGTAGTCACC
+
CCCCCGGGGEFGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGEFFGD@FGGGGGGGGGGGGEGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGFGGFGGGGGGGGEEGGGGGGGGGGGGGGGGFGGGFFGDGGGGGGGGGGGGGED<FEGFEFGGGEGGAEA8DCGGGFFFF;EEEFGGG>*;E2;>FDEC;=@EGEBFGGGGGGFFGG5CE8:*/*>GC=6AFFGFGG7;9/CEFGFFF*:?B442F:==44>5(937<*))2(399>:>FF?0228:))3>F>D(.2:A4.))),
```

test_2.fq
```
@M03580:15:000000000-AHFYP:1:1107:11796:2635 2:N:0:5
ATCTGGGACTACGCGGATTTCTAATCCTGTTTGCTCCCTACACTTTCGTCCCTCAATGTCAGTTTGTACTAAAACGTCTCTTTCGCTAATGCTGTTCCTCTCCATATTTTTGGCATTTATCCCTGAATATGTGAGTGTTCCTTTCTGTGCTCAACTCAAGTATCGCCGTATTATATCGTTGTTTACAGTTTCGCTGTAAGTTTTACCATATCACTTGTCATACACTCTACCGACGTGTTTCGCCGCGTACTGCTCTCCATACGTATCTCAAGACCGCTTAACGCAGCTCCTTGATCGTAGA
+
-@,@A-,@<<8F,@FB+8B@AFFGCGGECF,C<,CE@@E<C,C,E@FE,@FEGFDFFGCC,<F9<CCFFA@,,,,+:,6BFAFFGEG,8<E,9,C<54@,,,99,C,9,;=@+,9,C@,,,99,,,+,4,4,,,,9,9+++,63+3+?*>?+++)*3*58;;*2)0*3+0*++5+3?*:6)38)***+2+,+3:0*)3*31;*;+0*13*0***1*3*5;E=*0)0)000*11)))))0)2((--().(.8).))))()))(()/)(1.1)).((((((().(((((()((-))))-))0)
```

**Comment by mothur-westcott** [comment]
I can see the bug, and I will fix it.  If you run it with the file option, you won't see the error.

mothur > make.contigs(file=test.files)

>>>>>	Processing file pair test1.fastq.gz - test2.fastq.gz (files 1 of 1)	<<<<<
Making contigs...
1
Done.

It took 0 secs to assemble 1 reads.

It took 0 secs to process 1 sequences.


Output File Names: 
test.trim.contigs.fasta
test.trim.contigs.qual
test.contigs.report
test.scrap.contigs.fasta
test.scrap.contigs.qual

[WARNING]: your sequence names contained ':'.  I changed them to '_' to avoid problems in your downstream analysis.

**Comment by rec3141** [comment]
Hmm, there might be something weird about the gzip file itself. Can you try with the attached files? 
[test3.tar.gz](https://github.com/mothur/mothur/files/894611/test3.tar.gz)

**Comment by mothur-westcott** [comment]
When I ran them initially it failed.  When I gunzip and gzip them again I am not having an issue.  Could you see if that works for you?

**Comment by rec3141** [comment]
Yes I think I've determined that the bug occurs when processing files
formed by cat'ing several gz files together (as generally recommended on
SO) during a demultiplexing step in my pipeline. If any of the cat'ed files
are empty it gives the error. I think it would be great to see the bug
fixed because of its catastrophic nature (filling up hard drives and
hogging the processes) even though it may be a rare case.

**Comment by FBBJBB** [comment]
I had this issue too with the latest version 1.39.5 on mac OS 10.12.6.

**Comment by jdrum00** [comment]
Is the segfault on single pairs of .fq.gz files going to be fixed? I just started using mothur for the first time, and the very first thing I ran into was this year-old issue....

**Comment by raissafedora** [comment]
I'm still getting this error in 1.42.0. Is that a fix to this or is it my file's problem? thank you

**Comment by Fedorov113** [comment]
Experiencing it too, very frustrating.

**Comment by shodhak** [comment]
I am also facing the same issue.

**Comment by mothur-westcott** [comment]
I rebuilt the linux versions of 1.42.3, could you give them a try to see if this resolves the issue for you? https://github.com/mothur/mothur/releases/tag/v.1.42.3

**Comment by mothur-westcott** [comment]
#634 - will decompress files it can't read correctly
